### ISSUE TITLE
Dune API errors

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/dune-bridge#24]
Our cron-jobs updating Dune data are currently failing with:
> Dune API Request failed with errors [{'extensions': {'path': '$', 'code': 'validation-failed'}, 'message': 'query is not allowed'}]

It would be good to investigate why the "query is not allowed". If this is an intermittent issue, then we need to add some sort of retry mechanism because the alerts are quite noisy.

**Comment by bh2smith** [comment]
This is way old.
