### ISSUE TITLE
Use api auction endpoint instead of deprecated solvable_orders

### ISSUE THREAD

**Issue by vkgnosis** [cowprotocol/dune-bridge#29]
Currently this project is using the `solvable_orders` api endpoint https://github.com/cowprotocol/dune-bridge/blob/4c37f087ba345f6d34efd04fa5e8e44b740360c5/src/referral_maintenance.rs#L173-L192 .

It should be using the `get_auction` https://protocol-rinkeby.dev.gnosisdev.com/api/#/default/get_api_v1_auction endpoint.

**Comment by nlordell** [comment]
It should also not use the legacy URLs (`protocol-$network.gnosis.io`) but the new ones `api.cow.fi/$network`.

I would suggest this should be configurable.

**Comment by vkgnosis** [comment]
Bumping this issue @josojo .

**Comment by vkgnosis** [comment]
This was fixed in https://github.com/cowprotocol/dune-bridge/pull/32 .
